# \u6FC0\u6D3B\u4F7F\u7528\u54EA\u4E2A\u914D\u7F6E\u6587\u4EF6
# \u6FC0\u6D3B\u5F00\u53D1\u73AF\u5883\u7684\u914D\u7F6E\u6587\u4EF6application-dev.yml
# spring.profiles.active=dev

# \u4F7F\u7528application-test.yml\u914D\u7F6E\u6587\u4EF6
# spring.profiles.active=test

# \u4F7F\u7528application-online.yml\u914D\u7F6E\u6587\u4EF6
spring:
  profiles:
    active: online


